### ISSUE TITLE
Licensing weirdness, again

### ISSUE THREAD

**Issue by Hexstream** [theraphonics/simple-time#1]
Hello,

I'd like to help ensure you (re-)start this project on a solid base.

I am very puzzled by [the initial commit](https://github.com/theraphonics/simple-time/commit/e3d30d6ef6ab24671d98f60f867e6ca3e4bdd987), which just adds a `LICENSE` file which is then removed in [the second commit](https://github.com/theraphonics/simple-time/commit/3866768c02ea7b378d77865b38e7faa7fe06f270), which adds all the original code.

I've certainly never seen anything like this before.
Why not just use the current second commit as the initial commit?

**Comment by josharmenta** [comment]
You don’t need to open another issue about this. See the original Reddit thread. We have permission from the Copyright holder to fork the repo for embedded platform.No copy exists under source control. There is no repository. This was uploaded from CCRMA’s FTP repository manually.I uploaded a copy of the original repository and the original tar file to a locked branch to establish a starting point.That is the best we can do and Bil is okay with it.If you open another issue about this we’ll just block you from the repository.Sent from my iPhoneOn Mar 21, 2023, at 15:34, Jean-Philippe Paradis ***@***.***> wrote:﻿
Hello,
I'd like to help ensure you (re-)start this project on a solid base.
I am very puzzled by the initial commit, which just adds a LICENSE file which is then removed in the second commit, which adds all the original code.
I've certainly never seen anything like this before.
Why not just use the current second commit as the initial commit?

**Comment by josharmenta** [comment]
You don’t need to open another issue about this.

We have permission from the Copyright holder to fork the repo for embedded platform.

No copy exists under source control. There is no Github repository to fork.

This was uploaded from CCRMA’s FTP repository manually.

I uploaded a copy of the original repository and the original tar file to a locked branch to establish a starting point.

That is the best we can do and Bil is okay with it. That's why we are renaming the library.
